export const USER_EVENTS = {
    TAB_EVENT: 'TAB_EVENT',
    MOUSE_ENTER_EVENT: 'MOUSE_ENTER_EVENT',
    MOUSE_LEAVE_EVENT: 'MOUSE_LEAVE_EVENT',

    FORM_TEST_TITLE_EVENT: 'FORM_TEST_TITLE_EVENT',
    FORM_STUDENT_EVENT: 'FORM_STUDENT_EVENT',
    SOLUTION_CHECKBOX_EVENT: 'SOLUTION_CHECKBOX_EVENT',
    SOLUTION_RADIO_EVENT: 'SOLUTION_RADIO_EVENT',
    SOLUTION_TEXT_EVENT: 'SOLUTION_TEXT_EVENT',

    FORM_SOLUTION_SENT_EVENT: 'FORM_SOLUTION_SENT_EVENT',
    FORM_CHANGE_SOLUTION_EVENT: 'FORM_CHANGE_SOLUTION_EVENT',
    FORM_NEW_SOLUTION_EVENT: 'FORM_NEW_SOLUTION_EVENT',
    
    FORM_TRYING_TO_CLEAR_EVENT: 'FORM_TRYING_TO_CLEAR_EVENT',
    FORM_CANCEL_CLEAR_EVENT: 'FORM_CANCEL_CLEAR_EVENT',
    FORM_CLEARED_EVENT: 'FORM_CLEARED_EVENT',
};
